---
title: "nir"
output:
    html_document:
        df_print: paged
---



```{r, include=FALSE}
# knitr::opts_chunk$set(fig.width = 8, fig.height = 8)

# library(testit)

# library(readxl)
library(mvtnorm)
library(ggplot2)
# library(GGally) # pairwise plot
# library(stringr) # str_squish

# library(correlation) # cor_sort
library(tidyr)
# library(ppcor)
library(dplyr) # dataframe
library(reshape2)
# library(bbmle)
# library(graphics)

if (interactive()) setwd("R/nir/")
```


```{r}
# data_raw <- read.table("7.txt", header = TRUE)


data_raw <- rbind(
    read.table("1.txt", header = TRUE),
    read.table("2.txt", header = TRUE),
    read.table("3.txt", header = TRUE),
    read.table("4.txt", header = TRUE),
    read.table("5.txt", header = TRUE)
)

data_long <- data_raw %>%
    pivot_longer(cols = c(A, B), names_to = "struct", values_to = "time")

data <- data_long %>%
    group_by(n, m, struct) %>%
    summarise_all(mean)

# print(data)
```

```{r}
if (interactive()) pdf("point.pdf", width = 5, height = 5)
# dev.new(width = 5, height = 5, unit = "in")
ggplot(data_long) +
    geom_point(aes(x = n, y = time, color = struct))
if (interactive()) dev.off()
```



```{r}
if (interactive()) pdf("line.pdf", width = 5, height = 5)
ggplot() +
    geom_line(data = data, aes(x = n, y = time, color = struct))
if (interactive()) dev.off()
```

```{r}
if (interactive()) pdf("line_smooth.pdf", width = 5, height = 5)
ggplot() +
    geom_line(data = data, aes(x = n, y = time, color = struct)) +
    geom_smooth(data = data_long, aes(x = n, y = time, color = struct))
if (interactive()) dev.off()
```

```{r}
if (interactive()) pdf("relation.pdf", width = 5, height = 5)
ggplot(data_raw %>% group_by(n, m) %>% summarise_all(mean)) +
    geom_line(aes(x = n, y = B / A)) +
    geom_smooth(aes(x = n, y = B / A))
if (interactive()) dev.off()
```

```{r}
# ggplot() +
#     geom_point(data = data_raw, aes(x = A, y = B, color = n)) +
#     geom_abline(slope = 1, intercept = 0)
```

```{r}
# ggplot(data) +
#     geom_line(aes(x = n, y = log(time), color = struct, linetype = factor(m)))
```

```{r}
if (interactive()) pdf("line_smooth_norm.pdf", width = 5, height = 5)
ggplot() +
    geom_line(data = data, aes(x = n, y = time / n^4, color = struct)) +
    geom_smooth(data = data_long, aes(x = n, y = time / n^4, color = struct))
if (interactive()) dev.off()
```
