---
title: "Monte_Carlo"
output:
    html_document:
        df_print: paged
---



```{r, include=FALSE}
# knitr::opts_chunk$set(fig.width = 8, fig.height = 8)

# library(testit)

# library(readxl)
# library(reshape2)
library(ggplot2)
# library(GGally) # pairwise plot
# library(stringr) # str_squish

# library(correlation) # cor_sort
# library(tidyr) # drop.na()
# library(ppcor)
# library(dplyr) # dataframe
# setwd("R/Statistical_Analysis_2022/Partial_Correlation_CARDATA/Tkachenko")
```


```{r}
# plane = [A B C D]
# point = [x y z]
# point in area if Ax+By+Cz < D
# point on border if Ax+By+Cz = D
# point outside of area if Ax+By+Cz > D
check_linear_limit <- function(plane, point) {
    sum(plane[-length(plane)] * point) <= plane[length(plane)]
}

check_linear_limits <- function(planes, points) {
    if (is.null(dim(points))) {
        return(all(apply(planes, 1, check_linear_limit, point = points)))
    } else {
        return(apply(points, 1, check_linear_limits, planes = planes))
    }
}
```

```{r}
# x > 0
# t > bx
# v > cx
param_c <- 1
param_b <- 1
# linear_limits <- matrix(c(
#     c(-1, 0, 0, 0),
#     c(param_b, -1, 0, 0),
#     c(param_c, 0, -1, 0)
# ), nrow = 3, byrow = TRUE)
```

```{r}
# point = [x t v]
function24 <- function(point) {
    -2 / sqrt(pi) * sin(point[2]) / point[2] * exp(-point[3] * point[3])
}
```

```{r}
# point = [x t v]
function24_edited <- function(point) {
    t <- point[2] + param_b * point[1]
    v <- point[3] + param_c * point[1]
    -2 / sqrt(pi) * sin(t) / t * exp(-v * v)
}
```

```{r}
integrate <- function(N = 100000,
                      random_point_min = rep(0, 3),
                      random_point_max = rep(10, 3),
                      linear_limits = matrix(c(
                          c(-1, 0, 0, 0),
                          c(param_b, -1, 0, 0),
                          c(param_c, 0, -1, 0)
                      ), nrow = 3, byrow = TRUE),
                      f = function24) {
    # random_point_min <- c(0, 0, 0)

    # random_point_max <- rep(10, 3)
    random_points <- function(n = 1) {
        matrix(
            runif(3 * n) * (random_point_max - random_point_min)
                + random_point_min,
            ncol = 3, byrow = TRUE
        )
    }

    attempts <- 0
    filtered_points <- matrix(ncol = 3)

    while (dim(filtered_points)[1] < N) {
        attempts <- attempts + N - dim(filtered_points)[1]
        points <- random_points(N - dim(filtered_points)[1])

        points <- points[check_linear_limits(linear_limits, points), ]

        if (is.na(filtered_points[1, 1])) {
            filtered_points <- points
        } else {
            filtered_points <- rbind2(filtered_points, points)
        }
    }

    # print(filtered_points)
    # print(check_linear_limits(linear_limits, filtered_points))
    # print(attempts)

    volume <- prod(random_point_max - random_point_min) * N / attempts
    # distribution density (uniform)
    p <- 1 / volume


    # print(N)
    # print(p)
    # print(volume)
    # print(attempts)

    I <- mean(apply(filtered_points, 1, f)) / p
    I_ <- mean(apply(filtered_points, 1, function(x) abs(f(x)))) / p
    D <- mean(apply(filtered_points, 1, function(x) (f(x) - I)^2)) / p

    # return(c(I, I_, D))
    return(list(N = N, box_size = random_point_max[1], left = I - sqrt(D / N) * 1.96, right = I + sqrt(D / N) * 1.96))
}

integrate2 <- function(N = 100000,
                       random_point_min = rep(0, 3),
                       random_point_max = rep(10, 3),
                       linear_limits = matrix(c(c(-1, 0, 0, 0)), nrow = 1, byrow = TRUE),
                       f = function24_edited) {
    return(integrate(N, random_point_min, random_point_max, linear_limits, f))
}

# print(I)
```

```{r}
df1_box <- data.frame(rbind(
    integrate(random_point_max = rep(1, 3)),
    integrate(random_point_max = rep(5, 3)),
    integrate(random_point_max = rep(10, 3)),
    integrate(random_point_max = rep(50, 3)),
    integrate(random_point_max = rep(100, 3)),
    integrate(random_point_max = rep(500, 3))
))

df2_box <- data.frame(rbind(
    integrate2(random_point_max = rep(1, 3)),
    integrate2(random_point_max = rep(5, 3)),
    integrate2(random_point_max = rep(10, 3)),
    integrate2(random_point_max = rep(50, 3)),
    integrate2(random_point_max = rep(100, 3)),
    integrate2(random_point_max = rep(500, 3))
))
```

```{r}
df1_N <- data.frame(rbind(
    # integrate(N = 100),
    # integrate(N = 500),
    integrate(N = 1000),
    integrate(N = 2000),
    integrate(N = 5000),
    integrate(N = 10000),
    integrate(N = 20000)
    # integrate(N = 50000)
    # integrate(N = 100000)
))

df2_N <- data.frame(rbind(
    # integrate2(N = 100),
    # integrate2(N = 500),
    integrate2(N = 3 * 1000),
    integrate2(N = 3 * 2000),
    integrate2(N = 3 * 5000),
    integrate2(N = 3 * 10000),
    integrate2(N = 3 * 20000)
    # integrate2(N = 50000)
    # integrate2(N = 100000)
))
# integrate2(N = 100000)
```

```{r}
ggplot() +
    geom_line(data = df1_N, mapping = aes(y = as.numeric(left), x = log(3 * as.numeric(N), 10)), color = "red") +
    geom_line(data = df1_N, mapping = aes(y = as.numeric(right), x = log(3 * as.numeric(N), 10)), color = "red") +
    geom_line(data = df2_N, mapping = aes(y = as.numeric(left), x = log(as.numeric(N), 10)), color = "blue") +
    geom_line(data = df2_N, mapping = aes(y = as.numeric(right), x = log(as.numeric(N), 10)), color = "blue")
```


```{r}
ggplot() +
    geom_line(data = df1_box, mapping = aes(y = as.numeric(left), x = log(as.numeric(box_size), 10)), color = "red") +
    geom_line(data = df1_box, mapping = aes(y = as.numeric(right), x = log(as.numeric(box_size), 10)), color = "red") +
    geom_line(data = df2_box, mapping = aes(y = as.numeric(left), x = log(as.numeric(box_size), 10)), color = "blue") +
    geom_line(data = df2_box, mapping = aes(y = as.numeric(right), x = log(as.numeric(box_size), 10)), color = "blue")
```


